// Comes from sandbox.elastic.dev/test-books/apm/guide/transclusion/tab-widgets/install-agents/python.mdx

Django and Flask are two of several frameworks that the Elastic APM Python Agent
supports. For a complete list of supported technologies, refer to the
{apm-py-ref}/supported-technologies.html[Elastic APM Python Agent documentation].

++++
<div class="tabs" data-tab-group="transclusion-apm-guide-install-agents-python">
  <div role="tablist" aria-label="transclusion-apm-guide-install-agents-python">
    <button role="tab" aria-selected="true" aria-controls="transclusion-apm-guide-install-agents-python-django-panel" id="transclusion-apm-guide-install-agents-python-django-button">
      Django
    </button>
    <button role="tab" aria-selected="false" aria-controls="transclusion-apm-guide-install-agents-python-flask-panel" id="transclusion-apm-guide-install-agents-python-flask-button" tabindex="-1">
      Flask
    </button>
  </div>
  <div tabindex="0" role="tabpanel" id="transclusion-apm-guide-install-agents-python-django-panel" aria-labelledby="transclusion-apm-guide-install-agents-python-django-button">
++++
[source,python]
----
$ pip install elastic-apm
----

**1. Install the {apm-agent}**

Install the {apm-agent} for Python as a dependency.

[source,python]
----
$ pip install elastic-apm
----

**2. Configure the {apm-agent}**

Agents are libraries that run inside of your application process.
APM services are created programmatically based on the `SERVICE_NAME`.

[source,python]
----
. Add the agent to the installed apps
INSTALLED_APPS = (
  'elasticapm.contrib.django',
  . ...
)

ELASTIC_APM = {
  . Set required service name. Allowed characters:
  . a-z, A-Z, 0-9, -, _, and space
  'SERVICE_NAME': '',

  . Use if APM integration requires a token
  'SECRET_TOKEN': '',

  . Set custom APM integration host and port (default: http://localhost:8200)
  'SERVER_URL': '',
}

. To send performance metrics, add our tracing middleware:
MIDDLEWARE = (
  'elasticapm.contrib.django.middleware.TracingMiddleware',
  ....
)
----

++++
  </div>
  <div tabindex="0" role="tabpanel" id="transclusion-apm-guide-install-agents-python-flask-panel" aria-labelledby="transclusion-apm-guide-install-agents-python-flask-button" hidden="">
++++
**1. Install the {apm-agent}**

Install the {apm-agent} for Python as a dependency.

[source,python]
----
$ pip install elastic-apm[flask]
----

**2. Configure the {apm-agent}**

Agents are libraries that run inside of your application process.
APM services are created programmatically based on the `SERVICE_NAME`.

[source,python]
----
. initialize using environment variables
from elasticapm.contrib.flask import ElasticAPM
app = Flask(__name__)
apm = ElasticAPM(app)

. or configure to use ELASTIC_APM in your application settings
from elasticapm.contrib.flask import ElasticAPM
app.config['ELASTIC_APM'] = {
  . Set required service name. Allowed characters:
  . a-z, A-Z, 0-9, -, _, and space
  'SERVICE_NAME': '',

  . Use if APM integration requires a token
  'SECRET_TOKEN': '',

  . Set custom APM integration host and port (default: http://localhost:8200)
  'SERVER_URL': '',
}

apm = ElasticAPM(app)
----

++++
  </div>
</div>
++++

**Learn more in the {apm-agent} reference**

* {apm-py-ref}/supported-technologies.html[Supported technologies]
* {apm-py-ref}/configuration.html[Advanced configuration]
